[package]
name = "nocommit"
version = "0.1.0"
edition = "2021"

[dependencies]
atty = "0.2.14"
clap = { version = "4.5", features = ["derive"] }
reqwest = "0"
serde_json = "1"
tokio = { version = "1", features = ["rt", "macros", "rt-multi-thread"] }
